reptilerecon/reptilerecon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reptilerecon/', include('signal_extraction.urls', namespace='signal_extraction_ns')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reptilerecon/signal_extraction/urls.py
from django.urls import path

from . import views

app_name = 'YOLOv5'
urlpatterns = [
    path('', views.UploadVideoFormView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

reptilerecon/signal_extraction/models.py
from django.db import models
from django.dispatch import receiver
import os


class Video(models.Model):
    name = models.TextField(max_length=200, default="Sem nome")
    video = models.FileField(upload_to='videos/')
    processed_video = models.FileField(upload_to='processed_videos/', default=None, blank=True, null=True)
    signal = models.FileField(upload_to='signals/', default=None, blank=True, null=True)
    plot = models.FileField(upload_to='plots/', default=None, blank=True, null=True)
    thumbnail = models.ImageField(upload_to='thumbnails/', default=None)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.created_at)


@receiver(models.signals.post_delete, sender=Video)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.video:
        if os.path.isfile(instance.video.path):
            instance.video.delete(save=False)
            instance.processed_video.delete(save=False)
            instance.signal.delete(save=False)
            instance.plot.delete(save=False)
            instance.thumbnail.delete(save=False)

reptilerecon/signal_extraction/forms.py
from django.forms import ModelForm
from django import forms
from .models import Video
from django.utils.safestring import mark_safe
from django.forms import widgets

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class UploadVideoForm(forms.ModelForm):
    video = MultipleFileField(label='Select files', required=False)

    class Meta:
        model = Video
        fields = ['video', ]

reptilerecon/signal_extraction/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.core.files import File
from django.conf import settings
from django.core.exceptions import ValidationError
from django.views.decorators.csrf import csrf_exempt, csrf_protect

from .models import Video
from .forms import UploadVideoForm

import cv2
from PIL import Image
import io
import torch
import numpy as np
import pandas as pd
import os
import math
import plotly.express as px


class UploadVideoFormView(FormView):
    form_class = UploadVideoForm
    template_name = 'index.html'
    success_url = reverse_lazy('YOLOv5_nm:index')

    def __validate_file_extension(self, video_path):
        ext = os.path.splitext(video_path)[1]
        valid_extensions = ['.mp4']
        if not ext.lower() in valid_extensions:
            raise ValidationError('Unsupported file extension.')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('video')
        if form.is_valid():
            for f in files:
                self.__validate_file_extension(f.name)
            for f in files:
                video = Video(video=f)
                video_path = f.temporary_file_path()
                model = torch.hub.load(f"{settings.BASE_DIR}/yolov5", 'custom', path=f"{settings.BASE_DIR}/best.pt", source='local', force_reload=True)
                model.conf = 0.25
                video_capture = cv2.VideoCapture(video_path)
                width = int(video_capture.get(cv2.CAP_PROP_FRAME_WIDTH))
                height = int(video_capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
                video_output_path = f"{settings.MEDIA_ROOT}/result.mp4"
                fourcc = cv2.VideoWriter_fourcc(*'mp4v')
                video_writer = cv2.VideoWriter(video_output_path, fourcc, 30.0, (width, height))
                success, image = video_capture.read()
                coef_list = []
                x = 0.
                y = 0.
                while success:
                    results = model(image)
                    points = dict()
                    for result in results.pandas().xyxy[0].values:
                        x_min, y_min, x_max, y_max = map(round, result[:4])
                        class_id = result[6]
                        points[class_id] = (x_min, y_min, x_max, y_max)
                        if ("head" in points) and ("body" in points):
                            break
                    if ("head" in points) and ("body" in points):
                        image = cv2.rectangle(image, (points['head'][0], points['head'][1]), (points['head'][2], points['head'][3]), (255, 0, 0), 2)
                        image = cv2.putText(image, " head", (points['head'][0], points['head'][1]), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2, cv2.LINE_AA)
                        image = cv2.rectangle(image, (points['body'][0], points['body'][1]), (points['body'][2], points['body'][3]), (255, 0, 0), 2)
                        image = cv2.putText(image, " body", (points['body'][0], points['body'][1]), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2, cv2.LINE_AA)
                        x_mean_head = int((points['head'][0] + points['head'][2]) / 2)
                        y_mean_head = int((points['head'][1] + points['head'][3]) / 2)
                        x_mean_body = int((points['body'][0] + points['body'][2]) / 2)
                        y_mean_body = int((points['body'][1] + points['body'][3]) / 2)
                        cv2.line(image, (x_mean_head, y_mean_head), (x_mean_body, y_mean_body), (0, 255, 0), thickness=2)
                        cv2.circle(image, (x_mean_head, y_mean_head), radius=5, color=(0, 0, 255), thickness=-1)
                        cv2.circle(image, (x_mean_body, y_mean_body), radius=5, color=(0, 0, 255), thickness=-1)
                        video_writer.write(image)
                        difference = math.sqrt(math.pow(x - x_mean_head, 2) + math.pow(y - y_mean_head, 2))
                        x = x_mean_head
                        y = y_mean_head
                        if math.fabs(difference) > 1.5:
                            a1 = math.sqrt(math.pow(y_mean_body, 2) + math.pow(x_mean_body, 2))
                            a2 = math.sqrt(math.pow(y_mean_head - y_mean_body, 2) + math.pow(x_mean_head - x_mean_body, 2))
                            d = (math.pow(x, 2) + math.pow(y, 2) - math.pow(a1, 2) - math.pow(a2, 2)) / (2 * a1 * a2)
                            theta2 = math.atan(math.sqrt(1 - math.pow(d, 2)) / d)
                            coef_list.append(np.degrees(theta2))
                        else:
                            coef_list.append(np.NaN)
                    else:
                        coef_list.append(np.NaN)
                        video_writer.write(image)
                    success, image = video_capture.read()
                coef_list = np.round(coef_list, decimals=3)
                df = pd.Series(coef_list)
                df_tmp1 = df.rolling(3).mean()
                df_tmp2 = df.iloc[::-1].rolling(3).mean()
                df = df_tmp1.fillna(df_tmp2).fillna(df).interpolate(method='nearest').ffill().bfill()
                csv_output_path = video_output_path[0:-4] + '.csv'
                df.to_csv(csv_output_path)
                video_capture.release()
                video_writer.release()
                video_output_path_temp = video_output_path[0:-4] + 't.mp4'
                os.system(f"ffmpeg -i {video_output_path} -vcodec libx264 {video_output_path_temp} -y")
                os.rename(video_output_path_temp, video_output_path)
                figure = px.line(df)
                figure_output_path = os.path.join(settings.MEDIA_ROOT, "result.html")
                figure.write_html(figure_output_path)
                with open(video_output_path, 'rb') as f1, open(csv_output_path, 'rb') as f2,  open(figure_output_path, 'rb') as f3:
                    video.processed_video.save('result.mp4', File(f1), save=False)
                    video.signal.save('result.csv', File(f2), save=False)
                    video.plot.save('result.html', File(f3), save=False)
                video.name = video_path.split('/')[-1][0:-4]
                video_capture = cv2.VideoCapture(video_path)
                success, image = video_capture.read()
                image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                image_pil = Image.fromarray(image)
                image_io = io.BytesIO()
                image_pil.save(image_io, 'JPEG')
                video.thumbnail.save('thumb.jpg', File(image_io))

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        videos = Video.objects.all().order_by('-created_at')
        context = {
            'form': form,
            'videos': videos
        }
        return render(request, "YOLOv5/index.html", context)


class DetailView(generic.DetailView):
    model = Video
    template_name = 'YOLOv5/detail.html'


class DeleteView(generic.DeleteView):
    model = Video
    success_url = reverse_lazy('YOLOv5_nm:index')

reptilerecon/signal_extraction/templates/signal_extraction/base.html
<!doctype html>
<html lang="pt">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <title>{% block title %}Reptilerecon{% endblock %}</title>

        <style>
            video {
                width: 100%;
                height: auto;
            }
            #loader {
                display: none;
                position: fixed;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                width: 100%;
                height: 100%;
                background: rgba(0,0,0,0.75) no-repeat center center;
                z-index: 10000;
            }
            #spinner {
                margin: auto;
                position: absolute;
                top: 0;
                bottom: 0;
                left: 0;
                right: 0
            }

        </style>

    </head>
    <body class="bg-secondary font-family">
        <div class="container">
            <nav class="navbar navbar-light bg-secondary mb-5 rounded sticky-top shadow-lg">
                <div class="container-fluid d-flex flex-row justify-content-center justify-content-md-between">
                    <a href="{% url 'signal_extraction:index' %}" class="navbar-brand text-center col-12 col-md-auto">Reptilerecon</a>
                    {% block navbar %}
                    {% endblock navbar%}
                </div>
            </nav>
            {% block content %}
            {% endblock content%}
        </div>

         <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script>
        var spinner = $('#loader');
        $(function() {
          $('form').submit(function(e) {
            spinner.show();
          });
        });
        </script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        -->
    </body>
    <footer class="bg-light text-center text-lg-start mt-5">
        <div>

        </div>
        <div class="text-center p-3">
            © 2022 Copyright
        </div>
    </footer>
</html>

reptilerecon/signal_extraction/templates/signal_extraction/delete_modal.html
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal{{ video.id }}">
    Delete
</button>
<form action="{% url 'signal_extraction:delete' video.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="modal fade" id="modal{{ video.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="staticBackdropLabel">
                        Are you sure you want to delete this video?
                    </h4>
                </div>
                <div class="modal-body">
                    <img src="{{ video.thumbnail.url }}" class="card-img-top" alt="...">
                    <small class="text-muted modal-footer">
                        {{ video.created_at|date:'d-m-Y H:i' }}
                    </small>
                </div>
                <div class="modal-footer">
                    <div class="col-12 d-flex flex-row justify-content-evenly">
                        <div class="col-6 d-flex justify-content-evenly align-items-center">
                            <button type="button" class="btn btn-secondary d-flex" data-bs-dismiss="modal">Cancel</button>
                        </div>
                        <div class="col-6 d-flex justify-content-evenly align-items-center">
                            <button class="btn btn-outline-danger d-flex text-align-center" type="submit" value="Delete">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

reptilerecon/signal_extraction/templates/signal_extraction/detail.html
{% extends 'signal_extraction/base.html' %}

{% block navbar %}

    <div class="nav-item">
        <a class="btn btn-success" href="{% url 'signal_extraction:index' %}">Back</a>
    </div>
    <h3>{{ video.created_at|date:'d-m-Y H:i' }}</h3>

{% endblock navbar %}

{% block content %}
    <div class="card box-shadow m-2 p-2 bg-light shadow-lg">
        <fieldset>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            <div id="video_container" class="embed-responsive embed-responsive-16by9">
                <video id="video" width="400" class="embed-responsive-item" controls>
                    <source src="{{ video.processed_video.url }}" type="video/mp4">
                    Your browser does not support HTML5 video.
                </video>
            </div>
        </fieldset>
        <button type="button" id="play_button" class="btn btn-success">Play</button>
        <div>
            {% include video.plot.path %}
        </div>
    </div>
    <div class="col-12 d-flex flex-row justify-content-start">
        <div class="col-6 d-flex justify-content-start">
            <div class="d-flex me-2 my-2">
                <a type="button" class="btn btn-info" href="{{ video.processed_video.url }}" download>
                    Download video
                </a>
            </div>
            <div class="d-flex me-2 my-2">
                <a type="button" class="btn btn-info" href="{{ video.signal.url }}" download>
                    Download CSV
                </a>
            </div>
        </div>
        <div class="col-6 d-flex justify-content-end">
            <div class="d-flex me-2 my-2">
                {% include "signal_extraction/delete_modal.html" %}
            </div>
        </div>
    </div>

    <script>
        var playButton = document.getElementById("play_button");
        // Event listener for the play/pause button
        playButton.addEventListener("click", function() {
            if (video.paused == true) {
                // Play the video
                video.play();

                // Update the button text to 'Pause'
                playButton.innerHTML = "Pause";
            } else {
                // Pause the video
                video.pause();

                // Update the button text to 'Play'
                playButton.innerHTML = "Play";
            }
        });
    </script>

{% endblock %}

reptilerecon/signal_extraction/templates/signal_extraction/index.html
{% extends 'signal_extraction/base.html' %}

{% load index_tags %}

{% block navbar %}

    <form action="{% url 'signal_extraction:index' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="input-group">
            {{ form.video.errors }}
            {{ form.video }}
            <button type="submit" class="btn btn-success d-none d-md-block">
                Upload
            </button>
        </div>
        <div class="d-flex flex-row justify-content-center">
            <button type="submit" class="btn btn-success d-md-none d-flex mx-2 mt-2">
                Upload
            </button>
        </div>
    </form>
    <div id="loader">
        <div id="spinner" class="spinner-border text-success" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>

{% endblock navbar %}

{% block content %}
    <div class="row">
    {% for video in videos  %}
        <div class="col-sm-12 col-md-6">
            <div class="card box-shadow m-2 p-2 bg-light shadow-lg">
                <a role="button" href="{% url 'signal_extraction:detail' video.id %}">
                    <img src="{{ video.thumbnail.url }}" class="card-img-top" alt="...">
                </a>
                <div class="card-body">
                    <div class="row d-flex justify-content-center">
                        <div class="row col-md-12 d-flex flex-row">
                            <div class="col-12 col-md-8 d-flex justify-content-center justify-content-md-start align-items-baseline">
                                <h4 class="d-flex text-truncate" style="overflow-x: scroll;">{{ video.video.url|get_file_name }}</h4>
                            </div>
                            <div class="col-12 col-md-4 d-flex flex-column">
                                <div class="col-12 d-flex justify-content-center justify-content-md-end my-1">
                                    <small class="text-muted">
                                        {{ video.created_at|date:'d-m-Y H:i' }}
                                    </small>
                                </div>
                                <div class="col-12 d-flex justify-content-center justify-content-md-end my-1">
                                    {% include "signal_extraction/delete_modal.html" %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
             </div>
         </div>
    {% endfor %}
    </div>
{% endblock content %}